[package]
name = "proselint-registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
phf = { workspace = true }
regex = { workspace = true }
fancy-regex = { workspace = true }
