[project]
name = "proselint"
description = "A linter for prose."
license = {file = "LICENSE.md"}
authors = [{ name = "Amperser Labs", email = "hello@amperser.com"}]
readme = "README.md"
classifiers = [
	"Programming Language :: Python :: Implementation :: CPython",
	"Programming language :: Python :: 3",
	"Programming language :: Python :: 3.8",
	"Programming language :: Python :: 3.9",
	"Programming language :: Python :: 3.10",
	"Programming language :: Python :: 3.11",
	"Programming language :: Python :: 3.12",
	"License :: OSI Approved :: BSD License"
]
dynamic = ["version"]
requires-python = ">=3.8"
dependencies = [
	"typing_extensions>=4.9.0",
	"importlib-resources>=6.0; python_version<'3.9'",
	"cachetools>=5.4.0"
]

[project.urls]
Homepage = "https://proselint.com"
Repository = "https://github.com/amperser/proselint"
Issues = "https://github.com/amperser/proselint/issues"

[project.scripts]
proselint = "proselint.command_line:proselint"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
version = { source = "file", path = "proselint/version.py"}

[tool.pdm.scripts]

[tool.pdm.dev-dependencies]
test = [
	"coverage>=7.4.0",
	"mock>=2.0.0",
	"pytest>=7.0.0",
	"pytest-cov>=4.0.0",
	"rstr>=3.2.2",
]
dev = [
	"bumpversion>=0.5.3",
	"pre-commit>=3.5.0",
	"ruff>=0.1.14",
]
web = [
	"APScheduler>=3.5.3",
	"Flask-API>=1.0",
	"Flask-Cors>=3.0.4",
	"Flask>=1.1.4",
	"Flask-Limiter>=1.0.1",
	"gunicorn>=19.8.1",
	"gmail @ git+https://github.com/charlierguo/gmail.git",
	"redis>=2.10.6",
	"requests>=2.19.1",
	"rq>=0.12.0",
]

[tool.pdm.build]
includes = ["proselint/"]
source-includes = ["tests/"]
excludes = ["tests/.gitignore"]
