name: "CD: PyPI"
on:
  release:
    types: [created]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        python: ["3.10"]
    steps:
      - name: "[INIT] Checkout repository"
        uses: actions/checkout@v4
      - name: "[INIT] Install Python ${{ matrix.python }}"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: "[INIT] Install PDM"
        uses: pdm-project/setup-pdm@v4
        with:
          update-python: false
      - name: "[INIT] Restore dependency cache"
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
            .venv
          key: dev-${{ runner.os }}-${{ matrix.python }}-${{ hashFiles('**/pdm.lock') }}
      - name: "[INIT] Install dependencies"
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: pdm install -d --with dev
      - name: "[EXEC] Build"
        run: pdm build
      - name: "[EXEC] Publish to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
